//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCGIAY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBShopGiayEntities : DbContext
    {
        public DBShopGiayEntities()
            : base("name=DBShopGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINS { get; set; }
        public DbSet<BANNER> BANNERS { get; set; }
        public DbSet<CATEGORy> CATEGORIES { get; set; }
        public DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public DbSet<PRODUCT> PRODUCTS { get; set; }
        public DbSet<REVIEW> REVIEWS { get; set; }
        public DbSet<SUPPLIER> SUPPLIERS { get; set; }
    }
}
